# Generated by Django 3.0.6 on 2020-08-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchat',
            name='isword',
            field=models.BooleanField(default=True),
        ),
    ]
